/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI */

#ifndef _Included_org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI
#define _Included_org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI
 * Method:    callAdjMatrix
 * Signature: (Ljava/util/ArrayList;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI_callAdjMatrix
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI
 * Method:    callBaseBSearch
 * Signature: (Ljava/util/ArrayList;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI_callBaseBSearch
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI
 * Method:    callOptBSearch
 * Signature: (Ljava/util/ArrayList;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_hnu_precomputation_service_graphAlgo_graphCompute_egoBetweenness_JNI_callOptBSearch
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
